title: Jack Ho
description: Backend Engineer - Golang & Python
remote_theme: just-the-docs/just-the-docs

url: https://u0052041.github.io
baseurl: /golang-tour

search_enabled: true
footer_content: "Jack Ho - Backend Engineer"
color_scheme: light
